<?php include('header.php'); ?>
<style id='js_composer_front-inline-css' type='text/css'>
.vc_custom_1571318278589{background-color: #ff6d34 !important;}.vc_custom_1571317859336{padding-top: 30px !important;padding-right: 30px !important;padding-bottom: 25px !important;padding-left: 30px !important;border-radius: 10px !important;}.vc_custom_1571317859376{margin-top: 5px !important;margin-right: 30px !important;}.vc_custom_1571317872433{padding-top: 30px !important;padding-right: 30px !important;padding-bottom: 25px !important;padding-left: 30px !important;border-radius: 10px !important;}.vc_custom_1571317872474{margin-top: 1px !important;margin-right: 25px !important;}.vc_custom_1571317884171{padding-top: 30px !important;padding-right: 30px !important;padding-bottom: 25px !important;padding-left: 30px !important;border-radius: 10px !important;}.vc_custom_1571317884212{margin-top: 2px !important;margin-right: 28px !important;}.vc_custom_1571317895040{padding-top: 30px !important;padding-right: 30px !important;padding-bottom: 25px !important;padding-left: 30px !important;border-radius: 10px !important;}.vc_custom_1571317895079{margin-top: 5px !important;margin-right: 30px !important;}.vc_custom_1571317906314{padding-top: 30px !important;padding-right: 30px !important;padding-bottom: 25px !important;padding-left: 30px !important;border-radius: 10px !important;}.vc_custom_1571317906359{margin-top: 5px !important;margin-right: 30px !important;}.vc_custom_1571317918063{padding-top: 30px !important;padding-right: 30px !important;padding-bottom: 25px !important;padding-left: 30px !important;border-radius: 10px !important;}.vc_custom_1571317918103{margin-top: 5px !important;margin-right: 30px !important;}.vc_custom_1571319693471{margin-left: -33px !important;}.vc_custom_1569565570819{margin-bottom: 20px !important;border-left-width: 3px !important;padding-top: 0px !important;border-left-color: #dfdfdf !important;border-left-style: solid !important;}.vc_custom_1569565582733{margin-bottom: 20px !important;border-left-width: 3px !important;padding-top: 0px !important;border-left-color: #dfdfdf !important;border-left-style: solid !important;}.vc_custom_1569565589525{margin-bottom: 20px !important;border-left-width: 3px !important;padding-top: 0px !important;border-left-color: #dfdfdf !important;border-left-style: solid !important;}.vc_custom_1569565598812{margin-bottom: 20px !important;border-left-width: 3px !important;padding-top: 0px !important;border-left-color: #dfdfdf !important;border-left-style: solid !important;}.vc_custom_1569502682529{padding-left: 15px !important;}.vc_custom_1569502689762{padding-left: 15px !important;}.vc_custom_1569502697097{padding-left: 15px !important;}.vc_custom_1569502704943{padding-left: 15px !important;}
</style>
<div class="page-header page-header_align_center" style="background-image: url(http://iguru.wgl-demo.net/wp-content/uploads/2019/10/fag_page-title.jpg); background-size:cover; background-repeat:no-repeat; background-attachment:scroll; background-position:bottom center;background-color: #00bda6; height: 570px; margin-bottom: 40px; padding-top: 82px; padding-bottom: 0px;"><div class="page-header_wrapper"><div class="wgl-container"><div class="page-header_content"><h1 class="page-header_title" style="color: #ffffff; font-size: 48px; line-height: 72px;">FAQ`s</h1><div class="page-header_breadcrumbs" style="color: #ffffff; font-size: 14px; line-height: 24px;"><div class="breadcrumbs"><a href="http://iguru.wgl-demo.net/" class="home">Home</a> <span class="divider"></span> <span class="current">FAQ`s</span></div><!-- .breadcrumbs --></div></div></div></div></div>    <main id="main"><div class="wgl-container">
<div class="row">
<div id='main-content' class="wgl_col-12">
<div  class="vc_row wpb_row vc_row-fluid"><div class="wpb_column vc_column_container vc_col-sm-12 vc_col-lg-offset-2 vc_col-lg-8 vc_col-md-offset-1 vc_col-md-10"><div class="vc_column-inner "><div class="wpb_wrapper"><div  class ="iguru_module_spacing"><div class="spacing_size spacing_size-initial" style="height:40px;"></div></div>  
<div id=iguru_dlh_5f589bcede9c9 class="iguru_module_double_headings acenter "><div class="dlh_subtitle" style="font-size:16px; line-height:20px; "><span>SUPPORT CENTER</span></div><div class="dlh_title"  style="font-size: 48px; line-height:1.104; font-weight: 800; "><span>Select a Topic for Help</span></div></div><div  class ="iguru_module_spacing"><div class="spacing_size spacing_size-initial" style="height:23px;"></div></div>  
<div class="wpb_text_column wpb_content_element " >
<div class="wpb_wrapper">
<p style="text-align: center;">We&#8217;ll then ask you to tell us your current level of English or invite you to take our quick 20 minute placement test so we can make sure you start learning English.</p>
</div>
</div>
<div  class ="iguru_module_spacing"><div class="spacing_size spacing_size-initial" style="height:54px;"></div></div>  
</div></div></div></div><div  class="vc_row wpb_row vc_row-fluid vc_row-o-equal-height vc_row-flex"><div class="wpb_column vc_column_container vc_col-sm-6 vc_col-lg-4 vc_col-md-6"><div class="vc_column-inner "><div class="wpb_wrapper"><div id=iguru_infobox_5f589bcee04f6 class="iguru_module_infobox layout_left alignment_left"><div class="infobox_wrapper"><div class="infobox_icon_wrapper"><div class="infobox_icon_container" style="width: 50px; height: 48px;"><i class="infobox_icon flaticon-rocket"  style="font-size: 45px;"></i></div></div><div class="infobox_content_wrapper"><h3 class="infobox_title"  style="font-size: 18px;  font-weight: 800; margin-bottom: 4px; ">Getting Started</h3><div class="infobox_content" >How to start learning</div></div><div class="infobox_button_wrapper"><a href="#" class="infobox_button read-more-icon" ><i class="flaticon-arrow-1" style="font-size: 16px;"></i></a></div></div></div><div  class ="iguru_module_spacing"><div class="spacing_size spacing_size-initial" style="height:30px;"></div></div>  
</div></div></div><div class="wpb_column vc_column_container vc_col-sm-6 vc_col-lg-4 vc_col-md-6"><div class="vc_column-inner "><div class="wpb_wrapper"><div id=iguru_infobox_5f589bcee1327 class="iguru_module_infobox layout_left alignment_left"><div class="infobox_wrapper"><div class="infobox_icon_wrapper"><div class="infobox_icon_container" style="width: 55px; height: 48px;"><i class="infobox_icon flaticon-internet"  style="font-size: 45px;"></i></div></div><div class="infobox_content_wrapper"><h3 class="infobox_title"  style="font-size: 18px;  font-weight: 800; margin-bottom: 4px; ">Account/Profile</h3><div class="infobox_content" >Manage your account</div></div><div class="infobox_button_wrapper"><a href="#" class="infobox_button read-more-icon" ><i class="flaticon-arrow-1" style="font-size: 16px;"></i></a></div></div></div><div  class ="iguru_module_spacing"><div class="spacing_size spacing_size-initial" style="height:30px;"></div></div>  
</div></div></div><div class="wpb_column vc_column_container vc_col-sm-6 vc_col-lg-4 vc_col-md-6"><div class="vc_column-inner "><div class="wpb_wrapper"><div id=iguru_infobox_5f589bcee219f class="iguru_module_infobox layout_left alignment_left"><div class="infobox_wrapper"><div class="infobox_icon_wrapper"><div class="infobox_icon_container" style="width: 50px; height: 48px;"><i class="infobox_icon flaticon-target"  style="font-size: 45px;"></i></div></div><div class="infobox_content_wrapper"><h3 class="infobox_title"  style="font-size: 18px;  font-weight: 800; margin-bottom: 4px; ">Course Taking</h3><div class="infobox_content" >Everything about taking</div></div><div class="infobox_button_wrapper"><a href="#" class="infobox_button read-more-icon" ><i class="flaticon-arrow-1" style="font-size: 16px;"></i></a></div></div></div><div  class ="iguru_module_spacing"><div class="spacing_size spacing_size-initial" style="height:30px;"></div></div>  
</div></div></div><div class="wpb_column vc_column_container vc_col-sm-6 vc_col-lg-4 vc_col-md-6"><div class="vc_column-inner "><div class="wpb_wrapper"><div id=iguru_infobox_5f589bcee2ead class="iguru_module_infobox layout_left alignment_left"><div class="infobox_wrapper"><div class="infobox_icon_wrapper"><div class="infobox_icon_container" style="width: 50px; height: 48px;"><i class="infobox_icon flaticon-laptop"  style="font-size: 45px;"></i></div></div><div class="infobox_content_wrapper"><h3 class="infobox_title"  style="font-size: 18px;  font-weight: 800; margin-bottom: 4px; ">Troubleshooting</h3><div class="infobox_content" >Experiencing a bug?</div></div><div class="infobox_button_wrapper"><a href="#" class="infobox_button read-more-icon" ><i class="flaticon-arrow-1" style="font-size: 16px;"></i></a></div></div></div><div  class ="iguru_module_spacing"><div class="spacing_size spacing_size-initial" style="height:30px;"></div></div>  
</div></div></div><div class="wpb_column vc_column_container vc_col-sm-6 vc_col-lg-4 vc_col-md-6"><div class="vc_column-inner "><div class="wpb_wrapper"><div id=iguru_infobox_5f589bcee3a79 class="iguru_module_infobox layout_left alignment_left"><div class="infobox_wrapper"><div class="infobox_icon_wrapper"><div class="infobox_icon_container" style="width: 50px; height: 48px;"><i class="infobox_icon flaticon-browser"  style="font-size: 45px;"></i></div></div><div class="infobox_content_wrapper"><h3 class="infobox_title"  style="font-size: 18px;  font-weight: 800; margin-bottom: 4px; ">Mobile App</h3><div class="infobox_content" >Learn about our app</div></div><div class="infobox_button_wrapper"><a href="#" class="infobox_button read-more-icon" ><i class="flaticon-arrow-1" style="font-size: 16px;"></i></a></div></div></div><div  class ="iguru_module_spacing"><div class="spacing_size spacing_size-initial" style="height:30px;"></div></div>  
</div></div></div><div class="wpb_column vc_column_container vc_col-sm-6 vc_col-lg-4 vc_col-md-6"><div class="vc_column-inner "><div class="wpb_wrapper"><div id=iguru_infobox_5f589bcee444c class="iguru_module_infobox layout_left alignment_left"><div class="infobox_wrapper"><div class="infobox_icon_wrapper"><div class="infobox_icon_container" style="width: 50px; height: 48px;"><i class="infobox_icon flaticon-backup"  style="font-size: 45px;"></i></div></div><div class="infobox_content_wrapper"><h3 class="infobox_title"  style="font-size: 18px;  font-weight: 800; margin-bottom: 4px; ">Purchase/Refunds</h3><div class="infobox_content" >Learn about coupons</div></div><div class="infobox_button_wrapper"><a href="#" class="infobox_button read-more-icon" ><i class="flaticon-arrow-1" style="font-size: 16px;"></i></a></div></div></div><div  class ="iguru_module_spacing"><div class="spacing_size spacing_size-initial" style="height:30px;"></div></div>  
</div></div></div><div class="wpb_column vc_column_container vc_col-sm-12"><div class="vc_column-inner "><div class="wpb_wrapper"><div  class ="iguru_module_spacing"><div class="spacing_size spacing_size-initial" style="height:102px;"></div></div>  
</div></div></div></div><div  data-vc-full-width="true" data-vc-full-width-init="false" data-vc-stretch-content="true" class="vc_row wpb_row vc_row-fluid vc_custom_1571318278589 vc_row-has-fill"><div class="wpb_column vc_column_container vc_col-sm-12"><div class="vc_column-inner "><div class="wpb_wrapper"><div  class ="iguru_module_spacing"><div class="spacing_size spacing_size-initial" style="height:54px;"></div></div>  
<div class="iguru_module_clients clearfix anim-ex_images"><div class="iguru_module_carousel-wrapper"><div id=iguru_carousel_5f589bcee7b07 class="iguru_module_carousel pag_align_center"><div class="iguru_carousel_slick" data-slick='{"slidesToShow":6,"slidesToScroll":1,"infinite":true,"variableWidth":false,"autoplay":true,"autoplaySpeed":"3000","speed":300,"arrows":false,"dots":false,"adaptiveHeight":false,"responsive":[{"breakpoint":1025,"settings":{"slidesToShow":4,"slidesToScroll":1}},{"breakpoint":800,"settings":{"slidesToShow":2,"slidesToScroll":1}},{"breakpoint":480,"settings":{"slidesToShow":1,"slidesToScroll":1}}]}'><div class="clients_image"><div class="image_wrapper"><img class="main_image" src="http://iguru.wgl-demo.net/wp-content/uploads/2019/09/partners_1-w.png" alt="" /><img class="hover_image" src="http://iguru.wgl-demo.net/wp-content/uploads/2019/07/partners_1.png" alt="" /></div></div><div class="clients_image"><div class="image_wrapper"><img class="main_image" src="http://iguru.wgl-demo.net/wp-content/uploads/2019/09/partners_2-w.png" alt="" /><img class="hover_image" src="http://iguru.wgl-demo.net/wp-content/uploads/2019/07/partners_2.png" alt="" /></div></div><div class="clients_image"><div class="image_wrapper"><img class="main_image" src="http://iguru.wgl-demo.net/wp-content/uploads/2019/09/partners_3-w.png" alt="" /><img class="hover_image" src="http://iguru.wgl-demo.net/wp-content/uploads/2019/07/partners_3.png" alt="" /></div></div><div class="clients_image"><div class="image_wrapper"><img class="main_image" src="http://iguru.wgl-demo.net/wp-content/uploads/2019/09/partners_4-w.png" alt="" /><img class="hover_image" src="http://iguru.wgl-demo.net/wp-content/uploads/2019/07/partners_4.png" alt="" /></div></div><div class="clients_image"><div class="image_wrapper"><img class="main_image" src="http://iguru.wgl-demo.net/wp-content/uploads/2019/09/partners_5-w.png" alt="" /><img class="hover_image" src="http://iguru.wgl-demo.net/wp-content/uploads/2019/07/partners_5.png" alt="" /></div></div><div class="clients_image"><div class="image_wrapper"><img class="main_image" src="http://iguru.wgl-demo.net/wp-content/uploads/2019/09/partners_6-w.png" alt="" /><img class="hover_image" src="http://iguru.wgl-demo.net/wp-content/uploads/2019/07/partners_6.png" alt="" /></div></div><div class="clients_image"><div class="image_wrapper"><img class="main_image" src="http://iguru.wgl-demo.net/wp-content/uploads/2019/09/partners_7-w.png" alt="" /><img class="hover_image" src="http://iguru.wgl-demo.net/wp-content/uploads/2019/07/partners_7.png" alt="" /></div></div></div></div></div></div><div  class ="iguru_module_spacing"><div class="spacing_size spacing_size-initial" style="height:58px;"></div></div>  
</div></div></div></div><div class="vc_row-full-width vc_clearfix"></div><div  data-vc-full-width="true" data-vc-full-width-init="false" class="vc_row wpb_row vc_row-fluid vc_row-o-content-top vc_row-flex wgl-row-animation"><div class="wpb_column vc_column_container vc_col-sm-12"><div class="vc_column-inner "><div class="wpb_wrapper"><div  class ="iguru_module_spacing"><div class="spacing_size spacing_size-initial" style="height:55px;"></div></div>  
</div></div></div><div class="wpb_column vc_column_container vc_col-sm-12 vc_col-lg-6 vc_col-md-6"><div class="vc_column-inner vc_custom_1571319693471"><div class="wpb_wrapper"><div id="iguru_spacer_5f589bcee8819" class ="iguru_module_spacing responsive_active"><div class="spacing_size spacing_size-initial" style="height:25px;"></div><div class="spacing_size spacing_size-tablet" style="height:0px;"></div></div>  
<div id=iguru_img_layer_5f589bcee89e2 class="iguru_module_img_layer"><div class="img_layer_image_wrapper slide_left" style="z-index:2"><div class="img_layer_item" ><div class="img_layer_image"><img src="http://iguru.wgl-demo.net/wp-content/uploads/2019/10/faq_01-2.png" alt="" /></div></div></div><div class="img_layer_image_wrapper zoom_in" style="z-index:1"><div class="img_layer_item" ><div class="img_layer_image"><img src="http://iguru.wgl-demo.net/wp-content/uploads/2019/10/faq_01-1.png" alt="" /></div></div></div><div class="img_layer_image_wrapper zoom_in" style="z-index:2"><div class="img_layer_item" ><div class="img_layer_image"><img src="http://iguru.wgl-demo.net/wp-content/uploads/2019/10/faq_01-3.png" alt="" /></div></div></div><div class="img_layer_image_wrapper zoom_in" style="z-index:2"><div class="img_layer_item" ><div class="img_layer_image"><img src="http://iguru.wgl-demo.net/wp-content/uploads/2019/10/faq_01-4.png" alt="" /></div></div></div></div>  
</div></div></div><div class="wpb_column vc_column_container vc_col-sm-12 vc_col-lg-6 vc_col-md-6"><div class="vc_column-inner "><div class="wpb_wrapper"><div id="iguru_spacer_5f589bceea044" class ="iguru_module_spacing responsive_active"><div class="spacing_size spacing_size-initial" style="height:0px;"></div><div class="spacing_size spacing_size-tablet" style="height:30px;"></div></div>  
<div id=iguru_dlh_5f589bceea227 class="iguru_module_double_headings aleft "><div class="dlh_subtitle" style="font-size:16px; line-height:20px; "><span>FAQ &#039;S</span></div><div class="dlh_title"  style="font-size: 42px; line-height:1.143; font-weight: 800; "><span>Popular Questions</span></div></div><div  class ="iguru_module_spacing"><div class="spacing_size spacing_size-initial" style="height:30px;"></div></div>  
<div  class="vc_toggle vc_toggle_ vc_toggle_color_plus  vc_toggle_size_right vc_toggle_active"><div class="vc_toggle_title"><h4>What if I did not receive a password reset message?</h4><i class="vc_toggle_icon"></i></div><div class="vc_toggle_content"><p>Whether you want to develop as a professional or discover a new hobby, there&#8217;s an online course for that.</p>
</div></div><div  class="vc_toggle vc_toggle_ vc_toggle_color_plus  vc_toggle_size_right"><div class="vc_toggle_title"><h4>Where can I find my program certificate?</h4><i class="vc_toggle_icon"></i></div><div class="vc_toggle_content"><p>Whether you want to develop as a professional or discover a new hobby, there&#8217;s an online course for that.</p>
</div></div><div  class="vc_toggle vc_toggle_ vc_toggle_color_plus  vc_toggle_size_right"><div class="vc_toggle_title"><h4>How do I verify my identity?</h4><i class="vc_toggle_icon"></i></div><div class="vc_toggle_content"><p>Whether you want to develop as a professional or discover a new hobby, there&#8217;s an online course for that.</p>
</div></div><div  class="vc_toggle vc_toggle_ vc_toggle_color_plus  vc_toggle_size_right"><div class="vc_toggle_title"><h4>When does my course start and end?</h4><i class="vc_toggle_icon"></i></div><div class="vc_toggle_content"><p>Whether you want to develop as a professional or discover a new hobby, there&#8217;s an online course for that.</p>
</div></div><div  class="vc_toggle vc_toggle_ vc_toggle_color_plus  vc_toggle_size_right"><div class="vc_toggle_title"><h4>Can you help me select an enrollment my path?</h4><i class="vc_toggle_icon"></i></div><div class="vc_toggle_content"><p>Whether you want to develop as a professional or discover a new hobby, there&#8217;s an online course for that.</p>
</div></div><div  class ="iguru_module_spacing"><div class="spacing_size spacing_size-initial" style="height:30px;"></div></div>  
</div></div></div><div class="wpb_column vc_column_container vc_col-sm-12"><div class="vc_column-inner "><div class="wpb_wrapper"><div  class ="iguru_module_spacing"><div class="spacing_size spacing_size-initial" style="height:13px;"></div></div>  
</div></div></div><div class="wpb_column vc_column_container vc_col-sm-12"><div class="vc_column-inner "><div class="wpb_wrapper"><div class="vc_row wpb_row vc_inner vc_row-fluid"><div class="wpb_column vc_column_container vc_col-sm-6 vc_col-md-3 vc_col-has-fill"><div class="vc_column-inner vc_custom_1569565570819"><div class="wpb_wrapper"><div id=iguru_counter_5f589bceedb48 class="iguru_module_counter layout_top alignment_left "><div class="counter_content_wrapper"><div class="counter_value_placeholder" style="font-weight:800;"><span class="value_placeholder">589</span><div class="counter_value_wrapper" style="font-weight:800;"><span class="counter_value">589</span></div></div><div class="counter_title"  style="font-weight:500;">Creative Events</div></div></div></div></div></div><div class="wpb_column vc_column_container vc_col-sm-6 vc_col-md-3 vc_col-has-fill"><div class="vc_column-inner vc_custom_1569565582733"><div class="wpb_wrapper"><div id=iguru_counter_5f589bceee36a class="iguru_module_counter layout_top alignment_left "><div class="counter_content_wrapper"><div class="counter_value_placeholder" style="font-weight:800;"><span class="value_placeholder">147</span><div class="counter_value_wrapper" style="font-weight:800;"><span class="counter_value">147</span></div></div><div class="counter_title"  style="font-weight:500;">Skilled Tutors</div></div></div></div></div></div><div class="wpb_column vc_column_container vc_col-sm-6 vc_col-md-3 vc_col-has-fill"><div class="vc_column-inner vc_custom_1569565589525"><div class="wpb_wrapper"><div id=iguru_counter_5f589bceeeb4e class="iguru_module_counter layout_top alignment_left "><div class="counter_content_wrapper"><div class="counter_value_placeholder" style="font-weight:800;"><span class="value_placeholder">9</span><span class="value_suffix_placeholder">k+</span><div class="counter_value_wrapper" style="font-weight:800;"><span class="counter_value">9</span><span class="counter_value_suffix">k+</span></div></div><div class="counter_title"  style="font-weight:500;">Online Courses</div></div></div></div></div></div><div class="wpb_column vc_column_container vc_col-sm-6 vc_col-md-3 vc_col-has-fill"><div class="vc_column-inner vc_custom_1569565598812"><div class="wpb_wrapper"><div id=iguru_counter_5f589bceef36a class="iguru_module_counter layout_top alignment_left "><div class="counter_content_wrapper"><div class="counter_value_placeholder" style="font-weight:800;"><span class="value_placeholder">23</span><span class="value_suffix_placeholder">k+</span><div class="counter_value_wrapper" style="font-weight:800;"><span class="counter_value">23</span><span class="counter_value_suffix">k+</span></div></div><div class="counter_title"  style="font-weight:500;">People Worldwide</div></div></div></div></div></div></div><div  class ="iguru_module_spacing"><div class="spacing_size spacing_size-initial" style="height:65px;"></div></div>  
</div></div></div><div id="extended_5f589bceef6e5" class="particles-js" style="top:0%; left:0%; width:100%; height:100%; " data-particles-type="particles" data-particles-number="5" data-particles-color="#ff6d34,#00bda6,#f0f0f0" data-particles-line="false" data-particles-size="10" data-particles-speed="2" data-particles-hover="true" data-particles-hover-mode="grab" data-particles-colors-type="random_colors" ></div></div><div class="vc_row-full-width vc_clearfix"></div>
</div>
</div>
</div>
	</main>
    
    
    <style>#iguru_infobox_5f589bcee04f6 .infobox_icon {
color: #00bda6;
}#iguru_infobox_5f589bcee04f6 .infobox_wrapper:hover .infobox_icon {
color: #ff6d34;
}#iguru_infobox_5f589bcee04f6 .infobox_button { color: #b0bbc8; }#iguru_infobox_5f589bcee04f6 .infobox_button:hover { color: #b0bbc8; }#iguru_infobox_5f589bcee04f6 .infobox_wrapper {
background-color: #f9f9f9;				
}#iguru_infobox_5f589bcee04f6:hover .infobox_wrapper {
background-color: #ffffff;
}#iguru_infobox_5f589bcee04f6 .infobox_wrapper { padding-top: 30px !important;padding-right: 30px !important;padding-bottom: 25px !important;padding-left: 30px !important;border-radius: 10px !important; }#iguru_infobox_5f589bcee04f6 .infobox_icon_container { margin-top: 5px !important;margin-right: 30px !important; }#iguru_infobox_5f589bcee04f6 .infobox_wrapper { box-shadow: none; }#iguru_infobox_5f589bcee04f6:hover .infobox_wrapper {box-shadow: 6px 5px 25px 0px rgba(0,0,0,0.08);border-color: transparent;
}#iguru_infobox_5f589bcee1327 .infobox_icon {
color: #00bda6;
}#iguru_infobox_5f589bcee1327 .infobox_wrapper:hover .infobox_icon {
color: #ff6d34;
}#iguru_infobox_5f589bcee1327 .infobox_button { color: #b0bbc8; }#iguru_infobox_5f589bcee1327 .infobox_button:hover { color: #b0bbc8; }#iguru_infobox_5f589bcee1327 .infobox_wrapper {
background-color: #f9f9f9;				
}#iguru_infobox_5f589bcee1327:hover .infobox_wrapper {
background-color: #ffffff;
}#iguru_infobox_5f589bcee1327 .infobox_wrapper { padding-top: 30px !important;padding-right: 30px !important;padding-bottom: 25px !important;padding-left: 30px !important;border-radius: 10px !important; }#iguru_infobox_5f589bcee1327 .infobox_icon_container { margin-top: 1px !important;margin-right: 25px !important; }#iguru_infobox_5f589bcee1327 .infobox_wrapper { box-shadow: none; }#iguru_infobox_5f589bcee1327:hover .infobox_wrapper {box-shadow: 6px 5px 25px 0px rgba(0,0,0,0.08);border-color: transparent;
}#iguru_infobox_5f589bcee219f .infobox_icon {
color: #00bda6;
}#iguru_infobox_5f589bcee219f .infobox_wrapper:hover .infobox_icon {
color: #ff6d34;
}#iguru_infobox_5f589bcee219f .infobox_button { color: #b0bbc8; }#iguru_infobox_5f589bcee219f .infobox_button:hover { color: #b0bbc8; }#iguru_infobox_5f589bcee219f .infobox_wrapper {
background-color: #f9f9f9;				
}#iguru_infobox_5f589bcee219f:hover .infobox_wrapper {
background-color: #ffffff;
}#iguru_infobox_5f589bcee219f .infobox_wrapper { padding-top: 30px !important;padding-right: 30px !important;padding-bottom: 25px !important;padding-left: 30px !important;border-radius: 10px !important; }#iguru_infobox_5f589bcee219f .infobox_icon_container { margin-top: 2px !important;margin-right: 28px !important; }#iguru_infobox_5f589bcee219f .infobox_wrapper { box-shadow: none; }#iguru_infobox_5f589bcee219f:hover .infobox_wrapper {box-shadow: 6px 5px 25px 0px rgba(0,0,0,0.08);border-color: transparent;
}#iguru_infobox_5f589bcee2ead .infobox_icon {
color: #00bda6;
}#iguru_infobox_5f589bcee2ead .infobox_wrapper:hover .infobox_icon {
color: #ff6d34;
}#iguru_infobox_5f589bcee2ead .infobox_button { color: #b0bbc8; }#iguru_infobox_5f589bcee2ead .infobox_button:hover { color: #b0bbc8; }#iguru_infobox_5f589bcee2ead .infobox_wrapper {
background-color: #f9f9f9;				
}#iguru_infobox_5f589bcee2ead:hover .infobox_wrapper {
background-color: #ffffff;
}#iguru_infobox_5f589bcee2ead .infobox_wrapper { padding-top: 30px !important;padding-right: 30px !important;padding-bottom: 25px !important;padding-left: 30px !important;border-radius: 10px !important; }#iguru_infobox_5f589bcee2ead .infobox_icon_container { margin-top: 5px !important;margin-right: 30px !important; }#iguru_infobox_5f589bcee2ead .infobox_wrapper { box-shadow: none; }#iguru_infobox_5f589bcee2ead:hover .infobox_wrapper {box-shadow: 6px 5px 25px 0px rgba(0,0,0,0.08);border-color: transparent;
}#iguru_infobox_5f589bcee3a79 .infobox_icon {
color: #00bda6;
}#iguru_infobox_5f589bcee3a79 .infobox_wrapper:hover .infobox_icon {
color: #ff6d34;
}#iguru_infobox_5f589bcee3a79 .infobox_button { color: #b0bbc8; }#iguru_infobox_5f589bcee3a79 .infobox_button:hover { color: #b0bbc8; }#iguru_infobox_5f589bcee3a79 .infobox_wrapper {
background-color: #f9f9f9;				
}#iguru_infobox_5f589bcee3a79:hover .infobox_wrapper {
background-color: #ffffff;
}#iguru_infobox_5f589bcee3a79 .infobox_wrapper { padding-top: 30px !important;padding-right: 30px !important;padding-bottom: 25px !important;padding-left: 30px !important;border-radius: 10px !important; }#iguru_infobox_5f589bcee3a79 .infobox_icon_container { margin-top: 5px !important;margin-right: 30px !important; }#iguru_infobox_5f589bcee3a79 .infobox_wrapper { box-shadow: none; }#iguru_infobox_5f589bcee3a79:hover .infobox_wrapper {box-shadow: 6px 5px 25px 0px rgba(0,0,0,0.08);border-color: transparent;
}#iguru_infobox_5f589bcee444c .infobox_icon {
color: #00bda6;
}#iguru_infobox_5f589bcee444c .infobox_wrapper:hover .infobox_icon {
color: #ff6d34;
}#iguru_infobox_5f589bcee444c .infobox_button { color: #b0bbc8; }#iguru_infobox_5f589bcee444c .infobox_button:hover { color: #b0bbc8; }#iguru_infobox_5f589bcee444c .infobox_wrapper {
background-color: #f9f9f9;				
}#iguru_infobox_5f589bcee444c:hover .infobox_wrapper {
background-color: #ffffff;
}#iguru_infobox_5f589bcee444c .infobox_wrapper { padding-top: 30px !important;padding-right: 30px !important;padding-bottom: 25px !important;padding-left: 30px !important;border-radius: 10px !important; }#iguru_infobox_5f589bcee444c .infobox_icon_container { margin-top: 5px !important;margin-right: 30px !important; }#iguru_infobox_5f589bcee444c .infobox_wrapper { box-shadow: none; }#iguru_infobox_5f589bcee444c:hover .infobox_wrapper {box-shadow: 6px 5px 25px 0px rgba(0,0,0,0.08);border-color: transparent;
}@media only screen and (max-width: 991px){
#iguru_spacer_5f589bcee8819 .spacing_size{
display: none;
}					
#iguru_spacer_5f589bcee8819 .spacing_size-tablet{
display: block;
}
}#iguru_img_layer_5f589bcee89e2 .img_layer_image_wrapper:nth-child(1) .img_layer_image {transition: all 800ms; -webkit-transition-delay: 0ms; -moz-transition-delay: 0ms; -o-transition-delay: 0ms; transition-delay: 0ms;}#iguru_img_layer_5f589bcee89e2 .img_layer_image_wrapper:nth-child(2) .img_layer_image {transition: all 800ms; -webkit-transition-delay: 600ms; -moz-transition-delay: 600ms; -o-transition-delay: 600ms; transition-delay: 600ms;}#iguru_img_layer_5f589bcee89e2 .img_layer_image_wrapper:nth-child(3) .img_layer_image {transition: all 800ms; -webkit-transition-delay: 1200ms; -moz-transition-delay: 1200ms; -o-transition-delay: 1200ms; transition-delay: 1200ms;}#iguru_img_layer_5f589bcee89e2 .img_layer_image_wrapper:nth-child(4) .img_layer_image {transition: all 800ms; -webkit-transition-delay: 1800ms; -moz-transition-delay: 1800ms; -o-transition-delay: 1800ms; transition-delay: 1800ms;}@media only screen and (max-width: 991px){
#iguru_spacer_5f589bceea044 .spacing_size{
display: none;
}					
#iguru_spacer_5f589bceea044 .spacing_size-tablet{
display: block;
}
}#iguru_counter_5f589bceedb48 .counter_title {
color: #2c2c2c;
}#iguru_counter_5f589bceedb48 .counter_value_wrapper,
#iguru_counter_5f589bceedb48.layout_top .counter_content_wrapper {
color: #ff6d34;
}#iguru_counter_5f589bceedb48 .counter_content_wrapper{padding-left: 15px !important;}#iguru_counter_5f589bceee36a .counter_title {
color: #2c2c2c;
}#iguru_counter_5f589bceee36a .counter_value_wrapper,
#iguru_counter_5f589bceee36a.layout_top .counter_content_wrapper {
color: #ff6d34;
}#iguru_counter_5f589bceee36a .counter_content_wrapper{padding-left: 15px !important;}#iguru_counter_5f589bceeeb4e .counter_title {
color: #2c2c2c;
}#iguru_counter_5f589bceeeb4e .counter_value_wrapper,
#iguru_counter_5f589bceeeb4e.layout_top .counter_content_wrapper {
color: #ff6d34;
}#iguru_counter_5f589bceeeb4e .counter_content_wrapper{padding-left: 15px !important;}#iguru_counter_5f589bceef36a .counter_title {
color: #2c2c2c;
}#iguru_counter_5f589bceef36a .counter_value_wrapper,
#iguru_counter_5f589bceef36a.layout_top .counter_content_wrapper {
color: #ff6d34;
}#iguru_counter_5f589bceef36a .counter_content_wrapper{padding-left: 15px !important;}#iguru_soc_icon_wrap_5f589bcef251b a{
background: transparent;
}#iguru_soc_icon_wrap_5f589bcef251b a:hover{
background: transparent;
border-color: #00bda6;
}#iguru_soc_icon_wrap_5f589bcef251b a{
color: #acacae;
}#iguru_soc_icon_wrap_5f589bcef251b a:hover{
color: #ffffff;
}</style>
<?php 
include('footer.php');
?>